### ISSUE TITLE
Minimum disk option for cloud deploy?

### ISSUE THREAD

**Issue by dkj** [VertebrateResequencing/wr#1]
Our OpenStack flavors mostly have only 20TB volumes - how about specifying a minimum disk size (for "boot from image, copy to volume" if the flavor's disk is less than that requested)? I am anticipating wanting between 40TB and 300TB for temporary space.... Perhaps there is a better way of achieving this?

**Comment by sb10** [comment]
This is implemented on develop branch with the --disk option of `wr add`.
(And I'm hoping you mean GB and not TB...)

**Comment by sb10** [comment]
Oh, do you have a use-case for the "head" node having lots of disk space? I think in normal usage you would have a small head node for running `wr manager` (created by `wr cloud deploy`), and for particular commands that needed the disk space, you'd specify that in the JSON provided to `wr add`.

But I guess your #2 PR makes sense regardless, so I'll take a look.

**Comment by dkj** [comment]
Suspect a learning to drive wr problem on my part: I'd been specifying a flavor at cloud deploy to ensure I had 16 CPUs available for the jobs I want to run. But now realise I should probably rely on a properly constructed ```wr add``` causing an appropriate instance/server to be created.

**Comment by sb10** [comment]
Doing it that way is legitimate if the 16core flavor has enough other resources to run your 16 commands at once, and especially if they are fast to complete: this would mean completing much sooner compared to waiting for possibly 16 single core servers to come online.

But if you have long-running jobs and want to try doing things the "normal" way, FYI the flavor regex you need to use at the Sanger is '^m.*$' (ie. only use m flavors!).

In any case, thank you for the feature request and PR. Now implemented.
