### ISSUE TITLE
Native container support

### ISSUE THREAD

**Issue by sb10** [VertebrateResequencing/wr#104]
Can we run dockers "directly" and perhaps then have a better way of knowing how much memory etc. a command is using, and make things easier for users?

**Comment by keiranmraine** [comment]
If the container is started in such a way that WR can use the `docker stats` command you can see the memory and overall CPU usage as seen here:

https://docs.docker.com/engine/reference/commandline/stats/

It would also be useful if it was possible to tell WR that a process will use docker and that it should monitor `docker stats` (without a container id restriction).  This allows tools like dockstore to still be monitored but WR wouldn't be actively starting the docker container.

**Comment by keiranmraine** [comment]
https://github.com/VertebrateResequencing/wr/issues/23

**Comment by sb10** [comment]
I should look through all the docker API, but it may be possible to pull this information without needing the docker executable.

https://github.com/moby/moby/blob/3a633a712c8bbb863fe7e57ec132dd87a9c4eff7/client/container_stats.go could be the right thing?

**Comment by sb10** [comment]
https://github.com/moby/moby/blob/3a633a712c8bbb863fe7e57ec132dd87a9c4eff7/client/README.md

> The docker command uses this package to communicate with the daemon. It can also be used by your own Go applications to do anything the command-line interface does – running containers, pulling images, managing swarms, etc.

So yes, it should be possible...

**Comment by sb10** [comment]
Monitoring docker was implemented for fix of #35. Making it easy to start docker (at least if docker is installed) should also be possible. Will want some examples of how people run docker currently to see how to make that easier.

**Comment by keiranmraine** [comment]
1. Dockstore with file provisioning prior to cwltool starting a docker command
  * delay can be quite long before docker starts
2. Input/Output mounted from S3 with WR `mount` options. cwltool -> docker.
  * docker starts within seconds, but if a workflow I suspect many containers will be started over the life of the job.

Couple of options could help, but slightly work-around-ish

1. Ability to tell WR that a job must run isolated on an instance
  * this makes it easy to just monitor all docker containers that run on the instance
2. Users of cwltool can pass a `--singularity` flag (some other runners also support this)
  * then all mem/cpu will be attached to primary process

**Comment by sb10** [comment]
For the nextflow integration, and generally, it would be good to be able to add an option like `--with_docker imagename` or `--with_singularity imagename` when adding a command, and it would mean that image gets downloaded on the executing host if not already cached, the container is started up with cwd mounted inside, and the cmd executed inside.

This ought to be quite easy for Docker, but Singularity is not written in Go. Though I did read somewhere they were thinking about writing an API in Go. To investigate.

**Comment by sb10** [comment]
This has been implemented for what I think might be the common use case. See https://workflow-runner.readthedocs.io/en/latest/basics/add.html#containers for details.

If this isn't useful to you as-implemented, please let me know if there's some tweak or additional option that would make it useful.
