### ISSUE TITLE
Existing runners should be able to reconnect to new manager

### ISSUE THREAD

**Issue by sb10** [VertebrateResequencing/wr#107]
Currently, when a manager is shut down, it explicitly kills the jobs being executed in any runners first.
If the manager is lost for some other reason, runners keep executing their jobs and then try for many hours to save final state on the manager, but it's undefined what happens if the manager is started again.

We should have explicit support for existing runners being able to connect and resume normal operation on a new manager, and new managers shouldn't try to run jobs that were already running the last time the manager was working. (It's normal lost jobs mechanism would come in to play if some runners died.)

**Comment by sb10** [comment]
Now that we have token auth...

For runners reconnecting to new manager, manager will need to go out and delete all token files on all OS instances, and send the new file. Runners will need to check the timestamp on the token file, and if it changes, re-read it and try a new Connect().

**Comment by keiranmraine** [comment]
Would it make sense to be able to start a manager with a mode that allows the old token specifically for the use case of completing a `drain`, bring new instances up with a new one token?  New jobs only being sent to those with the new token.

**Comment by sb10** [comment]
Now implemented by re-using existing token files. It is not recommended you supply your own token to remain on the same token all the time though; this is only for recovery purposes.

If using your own cert and domain, there's an option that enables the whole OpenStack node that was running the manager to be destroyed, and when you bring up the manager on a new host (with new IP), old runners are still able to reconnect and continue running.
