### ISSUE TITLE
s3 different credentials for different mounts

### ISSUE THREAD

**Issue by keiranmraine** [VertebrateResequencing/wr#118]
We have a use case where we would like to be able to mount some ro data as inputs from one bucket but write results back to another bucket with _different_ credentials.

Would you consider extending the `--mount_json` syntax to allow inclusion of access and secret keys for each mount?  Using the default when not defined (read from local config I believe).

**Comment by sb10** [comment]
You can already do this by having named sections ("profiles") in your standard s3 config files, and selecting the desired profile in the mount syntax with profile@bucket.

**Comment by keiranmraine** [comment]
Thanks, I don't seem to be able to find this in the wiki section on mounts.

**Comment by sb10** [comment]
It's in the help text for `wr mount`. I've added this to the wiki as well.
