### ISSUE TITLE
cloud deploy times out if --resource_name char length is longer than 12

### ISSUE THREAD

**Issue by byb121** [VertebrateResequencing/wr#119]
We found that if we use more than 12 chars for `--resource_name`, `cloud deploy` times out and leaves `hostname is not a cloud instance` error captured from the remote.

**Comment by sb10** [comment]
Per https://stackoverflow.com/a/8725066/675083, looks like the maximum hostname length is 63; 50 of those are taken up by "wr-production--[uuid]", leaving the 12 limit you've encountered.

My proposed fix would be to have `wr cloud deploy` immediately fail if given a --resource_name longer than 12 chars.

Is that acceptable, or do you really need longer ones?

**Comment by byb121** [comment]
I think the proposed fix is fine. Although no limitation on the length is desired, 12 chars are good enough for our current use. Thanks,

**Comment by sb10** [comment]
Implemented. Actually, max length set to 11, to also work with development deployments.
