### ISSUE TITLE
Buried jobs should not be automatically retried on manager restart

### ISSUE THREAD

**Issue by dkj** [VertebrateResequencing/wr#120]
I find current behaviour surprising: consider scenario
- first attempt at job fails creating empty named file
- second attempt fixes problem and puts results in same named file
- manager shutdown and later restarted ready for separate new analysis but previously buried jobs are attempted again overwriting/zeroing the results of the successful jobs.

**Comment by sb10** [comment]
This is in a scenario where new jobs were added to fix the problem, and the first attempts left in buried state and not deleted before manager shutdown.

**Comment by sb10** [comment]
Buried state is now saved and restored from disk on start up.
