### ISSUE TITLE
Manager status from REST API

### ISSUE THREAD

**Issue by lbarbon** [VertebrateResequencing/wr#149]
Would it be possible to expose the wr manager status in the REST API?
When automating the submission of jobs to wr it would be useful to know, *e.g.* so we can stop submitting to wr manager instances that can't accept new jobs.

**Comment by sb10** [comment]
Yes, that's a good idea, thanks.

**Comment by sb10** [comment]
This is now implemented by doing a GET on the new /info/ endpoint. See the wiki for details. Until the next release, you'll have to make your own wr executable as per the README.md, using the develop branch.

**Comment by lbarbon** [comment]
Thank you very much, we tested the develop branch and it's working fine for us.
Since the new endpoint returns other pieces of information in addition to the manager status, we believe it might be useful if it also provided the version of the manager and, possibly, the set of REST API versions that it supports.

**Comment by sb10** [comment]
Yes, that also makes sense.

**Comment by sb10** [comment]
Versions now implemented at a new endpoint /rest/version, see updated wiki. A manager will only support the latest API version it knows about.

I had to do it an a new endpoint since if it's going to tell you about the API version, it can't be part of the API itself at the versioned addresses of all the other endpoints.

**Comment by lbarbon** [comment]
I noticed that the`/rest/version/` endpoint does not require the token header (maybe that's only required for `/rest/v1/*` routes?), while `/rest/v1/info/` does.

That may be reasonable, just checking that this is by design.

```sh
$ curl --cacert <CERTIFICATE> https://<URL>/rest/version/
{"Version":"v0.15.0-300-gff8f4b0","API":"1"}
$ curl --cacert <CERTIFICATE> https://<URL>/rest/v1/info/
Authorization header required
```

**Comment by sb10** [comment]
Yes, it's mentioned on the wiki that this is the only endpoint that doesn't need auth; it can't return any sensitive information.

If auth mechanism changes with future API versions, you need to find out the API version before authenticating.


> On 24 Oct 2018, at 11:57, lbarbon <notifications@github.com> wrote:
> 
> I noticed that the/rest/version/ endpoint does not require the token header (maybe that's only required for /rest/v1/* routes?), while /rest/v1/info/ does.
> 
> That may be reasonable, just checking that this is by design.
> 
> $ curl --cacert <CERTIFICATE> https://<URL>
> /rest/version/
> {
> "Version":"v0.15.0-300-gff8f4b0","API":"1"
> }
> $ curl --cacert 
> <CERTIFICATE> https://<URL>
> /rest/v1/info/
> Authorization header required
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by lbarbon** [comment]
Ok, thanks, I had missed that.
