### ISSUE TITLE
monitor_docker - wildcards

### ISSUE THREAD

**Issue by keiranmraine** [VertebrateResequencing/wr#163]
Some tools don't give full control when they create a cid file for running containers.  Having monitor_docker accept a string that could be expanded will prevent potential collisions if docker containers start very close together.

e.g. cwl-runner adds a date/timestamp to the dir/prefix your provide so something like the following would need to be glob expanded at run time:

`<UUID>-%.cid` would find the file with the corresponding uuid prefix with a timestamp such as `<UUID>-20181105140209-977190.cid`.

(this is not urgent, `?` should work for us, but we can see the potential cross-talk issue longer-term)

**Comment by sb10** [comment]
Thanks, this is useful and easy to implement, so can probably be done for the release after next.

**Comment by sb10** [comment]
Now implemented, using the more typical unix shell ? and * wildcards rather than %.
