### ISSUE TITLE
Enable logging in worker nodes

### ISSUE THREAD

**Issue by jmtcsngr** [VertebrateResequencing/wr#176]
Most of time is difficult to identify the root cause of issues with workers and jobs. Having local logs will significantly help to identify issues and check behaviour.
Some extra useful things to have will be:
* Rolling file appenders
* Configurable paths for logs (otherwise /tmp/something). As local file system may be small
* The option for workers nodes to send back logs to manager during normal executions/before they die
* For worker log options (verbosity, enabled/disabled, paths, etc) to be configurable from manager with a config file

**Comment by sb10** [comment]
As a start I've implemented this as a single non-configurable option to `wr manager start` called `--runner_debug`, that makes runners log to syslog.

If we really end up needing the extra configurabilty and ability to send logs to the manager, we can reopen this.
