### ISSUE TITLE
`wr version` creates .wr_production folder in HOME

### ISSUE THREAD

**Issue by jmtcsngr** [VertebrateResequencing/wr#185]
Not sure if this is expected behaviour, but find it strange so reporting.

If you have a clean home folder and execute `wr version`. It creates ~/.wr_production folder. Which to me is strange since I just wanted to see the version without changing the state of the user's home folder.

**Comment by sb10** [comment]
I agree, this is not ideal. I'll look in to it.

**Comment by sb10** [comment]
Fixed; now maoagerdir is only created during `wr manager start`.
