### ISSUE TITLE
Job management from REST API

### ISSUE THREAD

**Issue by lbarbon** [VertebrateResequencing/wr#190]
Would it be possible to expose the ability to stop and/or cancel a pending or running job through the REST API? I believe at the moment that functionality is only available through the web interface used by the wr web client.

**Comment by sb10** [comment]
Hi, thanks for making this request. Yes, killing and removing jobs is only possible with the web or command line interface.

It is possible for this to be added to the REST API as well. I'll add this to the to-do list.

**Comment by lbarbon** [comment]
Thank you very much. Would you be able to provide an approximate time frame for this addition?

**Comment by sb10** [comment]
Perhaps by the end of March. A release with other features needs to go out first.

**Comment by sb10** [comment]
Implemented in https://github.com/VertebrateResequencing/wr/pull/195 ; please comment and let me know if you'd like to officially review this PR.

Wiki updated on how to use it: https://github.com/VertebrateResequencing/wr/wiki/REST-API (DELETE /rest/v1/jobs/).

Once reviewed, this should be part of the next release (0.18) of wr.

**Comment by lbarbon** [comment]
Thanks. I will test the functionality and take a look at the code, but I am not sufficiently familiar with Go for a formal review.

**Comment by sb10** [comment]
Now implemented.
