### ISSUE TITLE
Have managerumask apply to remote runners

### ISSUE THREAD

**Issue by mgcam** [VertebrateResequencing/wr#191]
Currently getting -rw-r--r-- on output files. Would like to be able to set to -rw-rw-r--

**Comment by sb10** [comment]
The managerumask config option sets the umask of the manager daemon process (and anything it directly spawns: local runners).

It makes sense for this to also apply to runners when they are spawned on remote machines.

**Comment by sb10** [comment]
Fixed in https://github.com/VertebrateResequencing/wr/pull/196 ; care to review it? It's straight-forward.

**Comment by sb10** [comment]
Implemented, though OpenStack-specific. Kubernetes scheduler still uses default umask.
