### ISSUE TITLE
Pin manager to different cloudflavor

### ISSUE THREAD

**Issue by keiranmraine** [VertebrateResequencing/wr#201]
I'd like to ensure that the manager process is pinned to a `^m.*$` flavour, but allow `^m.*|s.*$` for spawned workers.  Does the exiting configuration allow for this other than by defining `--cloud_flavor` during add?

**Comment by sb10** [comment]
It's not currently possible to specify a different regex (or explicit flavor) for the manager server created by `wr cloud deploy`, compared to what is used for workers.
I agree it's useful to enable this. I can add a --manager_flavor option to `wr cloud deploy`. It would be easiest and trivial to implement this as a flavor regex, but perhaps this should only take an explicit and complete flavor name?

**Comment by keiranmraine** [comment]
I don't think it being a regex is really an issue, users can still force it to be a specific type using that.  In our case `^m\d+\.tiny$` would be a useful option as the digit changes as old/new hardware cycles.

**Comment by sb10** [comment]
Now implemented as a `--manager_flavor` option to deploy and a cloudflavormanager config option.
