### ISSUE TITLE
Disk usage measurement is doubled with mount in subdir

### ISSUE THREAD

**Issue by sb10** [VertebrateResequencing/wr#211]
When specifying an uncached write mount in a subdir of the cwd, creating a file in the cwd, and then copying the file in to the mount, wr status reports that the task uses double the space it actually uses.

**Comment by keiranmraine** [comment]
Follow up from email.  In my case I'm interested in the "cached" data being reported for `ro` mounts. Possibly information about cached data should be in a separate metric.  I agree copying data into a mount shouldn't be considered.

**Comment by sb10** [comment]
How did you do the mount exactly? Can you share the JSON or command line arg (you can censor the bucket location)?

**Comment by keiranmraine** [comment]
Pretty standard, submitted through REST api:

```json
[
  {
    "Mount": "mnt/XXX-results/casm/cit-github/cgppindel/feature-addlarge/TARGETED-regression-1",
    "Targets": [
      {
        "Profile": "default",
        "Path": "XXX-results/casm/cit-github/cgppindel/feature-addlarge/TARGETED-regression-1",
        "Write": true
      }
    ]
  },
  {
    "Mount": "mnt/data/mt",
    "Targets": [
      {
        "Profile": "default",
        "Path": "XXX-data/TARGETED/regression-1/PD23367a_empty",
        "Cache": true
      }
    ]
  },
  {
    "Mount": "mnt/data/ref",
    "Targets": [
      {
        "Profile": "default",
        "Path": "XXX-ref/human/GRCh37d5",
        "Cache": true
      }
    ]
  },
  {
    "Mount": "mnt/data/wt",
    "Targets": [
      {
        "Profile": "default",
        "Path": "XXX-data/TARGETED/regression-1/PD23336b",
        "Cache": true
      }
    ]
  }
]
```

I don't know that this does or doesn't get counted at present, just that the following would be a good way to report this

| Peak Disk (cached) |
|--------------------|
| 2 GB (1GB) |

**Comment by sb10** [comment]
Sorry for the extraordinary delay in fixing this, but I think https://github.com/VertebrateResequencing/wr/pull/404 will resolve this. It will be in the next release due at the end of the month.
