### ISSUE TITLE
wr mod resumes manager regardless of the manager state before the mod started

### ISSUE THREAD

**Issue by jmtcsngr** [VertebrateResequencing/wr#224]
If a wr mod is executing while a manager is paused, the mod operation will finish by resuming the manager. I think the mod operation should leave the manager paused if it was so before the mod operation was executed. Pausing the manager before any mod operation makes perfect sense to me. But will prefer for the mod operation to leave the manager in the same state it was before the mod operation started.

**Comment by sb10** [comment]
Fixed in next release.
