### ISSUE TITLE
Ability to launch multiple cloud instances simultaneously without waiting

### ISSUE THREAD

**Issue by tnguyensanger** [VertebrateResequencing/wr#248]
From v0.20.0-10-g8bd544d-dirty, we found that it took 1 minute to launch each cloud instance.    For example, if we wanted to run 60 jobs, we would have to wait an hour for all of them to kickoff.  This makes debugging, development, and running of pipelines time consuming.  From private correspondance, we were provided a test a binary in which a --cloud_spawns parameter was added and that successfully launched multiple cloud instances simultaneously.

**Comment by sb10** [comment]
Implemented in https://github.com/VertebrateResequencing/wr/pull/243, thanks
