### ISSUE TITLE
OpenStack scheduler: memory usage is wrong

### ISSUE THREAD

**Issue by sb10** [VertebrateResequencing/wr#35]
Keiran reports that the memory usage reported for his jobs is wrong when running in OpenStack; may be related to use of Docker?

Jobs report a peak of ~700MB RAM, but on the running host it's more like 7-8GB:

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
     1493 ubuntu    20   0   95524   2784   1636 S   0.0  0.0   0:00.08 sshd: ubuntu@notty                   
     1500 ubuntu    20   0   22108   5152    888 S   0.0  0.0   0:43.28 /tmp/wr runner -q cmds -s 16384:60:8:
    19710 ubuntu    20   0   11248   1808   1616 S   0.0  0.0   0:00.00 bash -c echo '{ "reference": { "path"
    19711 ubuntu    20   0   11312   1980   1700 S   0.0  0.0   0:00.00 bash /usr/local/bin/dockstore tool la
    19740 ubuntu    20   0 19.198g 1.104g   8020 S   0.0  1.8  19:44.48 java io.dockstore.client.cli.Client t
    19859 ubuntu    20   0   69888  30496   4928 S   0.0  0.0   0:00.63 /usr/bin/python /usr/local/bin/cwltoo
    19882 ubuntu    20   0  382048  15340  10160 S   0.0  0.0   0:01.03 docker run -i --volume=/tmp/./datasto
    19954 ubuntu    20   0   18052   2828   2564 S   0.0  0.0   0:00.13 /bin/bash /opt/wtsi-cgp/bin/mapping.s
    19989 ubuntu    20   0    4364    652    580 S   0.0  0.0   0:00.00 /usr/bin/time -f command:%C\nreal:%e\
    19990 ubuntu    20   0  158312  35384   4600 S   0.0  0.1   0:00.54 /usr/bin/perl /opt/wtsi-cgp/bin/bwa_m
    20016 ubuntu    20   0    4508    844    764 S   0.0  0.0   0:00.00 sh -c /usr/bin/time /var/spool/cwl/tm
    20017 ubuntu    20   0    4232    624    556 S   0.0  0.0   0:00.00 /usr/bin/time /var/spool/cwl/tmpMap_L
    20018 ubuntu    20   0    9576   2536   2336 S   0.0  0.0   0:00.00 /bin/bash /var/spool/cwl/tmpMap_LP600
    20019 ubuntu    20   0 14.027g 5.985g   3696 S 691.7  9.5   2110:14 /opt/wtsi-cgp/bin/bwa mem -Y -K 10000
    20020 ubuntu    20   0    7652   4040   1228 S   6.3  0.0   3:58.94 /opt/wtsi-cgp/bin/reheadSQ -d /var/sp
    20021 ubuntu    20   0 1254028 1.045g   8144 R  55.1  1.7  21:41.23 /opt/wtsi-cgp/bin/bamsort fixmate=1 i

**Comment by keiranmraine** [comment]
Added possible route to handle this on #23

**Comment by sb10** [comment]
Now fixed, for docker cmds at least, with new --monitor_docker option.
