### ISSUE TITLE
OpenStack server destroy should allow user shutdown script

### ISSUE THREAD

**Issue by sb10** [VertebrateResequencing/wr#419]
Currently, when a server is destroyed it syncs the filesystem and attempts (but can't verify) a ro-remount of all filesystems.

This should avoid any data corruption, but on server-client filesystems like lustre, the server gets unhappy if the client doesn't do a clean and full unmount.

We can't do that generically because we don't know which filesystems can be unmounted while the system is still up (we have to run the command over ssh).

Therefore we should allow a user-definable script to be run prior to server destruction (eg. `/usr/lib/sbin/mountLustre stop`) with a user-definable timeout (eg. 3mins).

**Comment by jbeal-work** [comment]
I don't think you need the timeout although it is a convience, there is a unix command [https://man7.org/linux/man-pages/man1/timeout.1.html](timeout) which could be used. I am not sure which way would be less work in the long run.

Thanks.

**Comment by sb10** [comment]
The timeout would be necessary since we can't risk just leaving a server up forever because the user's script got stuck.

However, the timeout would be implemented as a timeout on running the script over ssh, so we wouldn't need to use `timeout`.

Regardless of how the attempt at running the user script goes (the scripts exits 0, non-0, the ssh fails entirely, the ssh times out), we'd terminate the server after the attempt.

So you will still expect to see some low quantity of evictions on lustre, but less than currently.

**Comment by jbeal-work** [comment]
That sounds fine.

**Comment by sb10** [comment]
This was implemented using the same fixed 15min timeout that the user boot-up script uses, since it shared the same code.

I'd hope 15mins would be enough for anything non-broken.
