### ISSUE TITLE
Job status should indicate disk full state

### ISSUE THREAD

**Issue by keiranmraine** [VertebrateResequencing/wr#43]
Jobs using the `--disk` option can appear running when the device has filled.

**Comment by sb10** [comment]
Do you mean that the status webpage shows a blue "running" bar for the cmd, but when you ssh to the node the cmd is running on, there is no process for it because it exited due to running out of disk space?

**Comment by keiranmraine** [comment]
Actually the job 'appears' to think it's still running but there's `tee` usage on the output stream of the underlying process which may be complicating issues.

**Comment by sb10** [comment]
Sorry, can you clarify? Is the command you give wr still running when the device has filled? But you're running some complex command where your "real" work is some forked process or similar that fails silently? There's not much wr can do in this case; you'll need to formulate your command such that it exits non-zero when it encounters problems.

If I've misunderstood, please supply the command you're trying to run. (email me if it's sensitive in nature)

**Comment by keiranmraine** [comment]
@sb10, can I re-raise this with a more generic purpose?

WR should flag jobs on hosts where storage device(s) at 100% when tested with `df` with similar options to those described in https://github.com/VertebrateResequencing/wr/issues/73#issuecomment-288992711.

Even if not flagged it would be useful information to add to the web interface for failed jobs.

**Comment by sb10** [comment]
Agreed.

**Comment by sb10** [comment]
Heartbeat ticker should regularly check disk space with `df`, and kill itself with an explanatory end state if 100%.

**Comment by sb10** [comment]
Now implemented.
