### ISSUE TITLE
Can't get autocomplete to work

### ISSUE THREAD

**Issue by muffato** [VertebrateResequencing/wr#434]
Hi,

I downloaded the latest `wr` (https://github.com/VertebrateResequencing/wr/releases/download/v0.29.0/wr-linux-x86-64.zip) and wanted to test the autocompletion, but it seems to be missing some things:
```
$ ./wr completion bash > wr_aucomplete.sh
$ source wr_aucomplete.sh 
$ wr [TAB] _get_comp_words_by_ref: command not found
```

I'm on a Ubuntu 18.04.6 LTS, but it's not 100% clear which version of bash is installed
```
$ bash --version
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
$ dpkg -l | grep bash
ii  bash                 4.4.18-2ubuntu1.2          amd64        GNU Bourne Again SHell
ii  bash-completion      1:2.8-1ubuntu1             all          programmable completion for the bash shell
```

**Comment by sb10** [comment]
Hi, unfortunately it seems the bash autocomplete feature will only work if you build wr yourself on the machine you want to use wr on.

I've added to the docs to explain this: https://workflow-runner.readthedocs.io/en/latest/basics/install.html#bash-auto-completion

The release you can download was built on a farm5 head node, so you can try out the feature there if you like.

I'm going to close this, but please re-open it if it still doesn't work after building yourself.

**Comment by muffato** [comment]
Hi. I've made some progress on this: I've found out that it doesn't work when I'm in a `screen` session, but it works otherwise. I guess the shell initialisation of within `screen` is not entirely the same as the login shell
