### ISSUE TITLE
Provide option to let wr manager know a worker needs to be destroyed

### ISSUE THREAD

**Issue by jmtcsngr** [VertebrateResequencing/wr#441]
We hit an issue where we were aware a specific worker was causing issues. To release the worker we paused the manager and waited until all jobs in the worker were complete so it could go to deathrow. We didn't want to just kill the worker manually because we were afraid it will be destroyed without flushing IO cache to shared filesystem. We wanted wr manager to execute stop script and destroy. Guess these steps could be mimicked manually, go inside the worker, kill all jobs, execute stop script manually and then manually kill the worker. But it will be nice to have something more automatic. It is a very outlier case but will be interesting to have an option to let the manager know a worker needs to stop getting new jobs. Or to have commands to control life cycle of workers.

Thanks!

**Comment by sb10** [comment]
I believe something like a `wr cloud servers --destroy <server identifier>` command could be developed, however it may be early June before I can develop and release this new feature. Can you wait that long, or is it urgent?

**Comment by jmtcsngr** [comment]
Sound great!

Not urgent. Just for the wishlist please.

Having the option to decide between a "drain" and a "destroy immediately" will be great. But having destroy should be good enough for most of scenarios I think.

**Comment by sb10** [comment]
Sorry for the extraordinary delay, but this is now done, and will be in the next release, due shortly.

Just note that --destroy takes a host name only, not the id that -i takes when using --confirmdead.
