### ISSUE TITLE
`parseBjobs` fails with long jobnames

### ISSUE THREAD

**Issue by mcshane** [VertebrateResequencing/wr#446]
Getting the following error in the log file which is due to some extremely long jobnames (from non-`wr` jobs submitted) which is then leading to a failed parsing of the `bjobs -w` output. Leads to no jobs being run through `wr`
```
t=2023-01-06T12:58:56+0000 lvl=warn msg="Server scheduling runners error" err="scheduler(lsf) parseBjobs(): failed to read everything from [bjobs -w]: bufio.Scanner: token too long" caller=jobqueue/server.go:2467
```

**Comment by sb10** [comment]
Sorry about that. Do you have an example name, or the length of it?

**Comment by muffato** [comment]
About 15k bytes. The command itself is `gzip --best file1 file2 ...`

**Comment by sb10** [comment]
Where is this? I don't see any very long names on farm5 or tol farm.

**Comment by mcshane** [comment]
@muffato kindly just renamed the jobs, so they're not there anymore. So, urgency of this is low, but just wanted to make sure I flagged it in case it comes up again.

**Comment by sb10** [comment]
OK, well this will in theory be fixed in the next release, but I haven't tested it in reality. Thanks for the bug report!
