### ISSUE TITLE
OpenStack - teardown when bad password

### ISSUE THREAD

**Issue by keiranmraine** [VertebrateResequencing/wr#47]
If you mistype your password when sourcing the OpenStack API file and then call teardown you get an authentication error as you would expect.  This results in having to do a `--force` teardown.

Could the command be a little more resilient and check for auth before going into an unrecoverable state.

Use case: this could catch user error as is if the password is wrong you may be attempting to teardown the wrong tenant.

**Comment by sb10** [comment]
To clarify, you don't want teardown to shut down the remote manager before checking the auth? Yes, that's a good idea.

**Comment by sb10** [comment]
now implemented
