### ISSUE TITLE
OpenStack scheduler: timed-out servers leave behind volumes

### ISSUE THREAD

**Issue by keiranmraine** [VertebrateResequencing/wr#48]
It appears that when submitting a large number of jobs requiring the `--disk` option that as the system scales up wr abandons the volume request and starts a new one.

This results in unattached volumes periodically in the scale up process which can eat the tenant allocation.

Seems to be reproducible with 1.5TB volumes.

**Comment by keiranmraine** [comment]
@sb10 , this looks to be a glance/ceph performance issue but I've temporarily patched my copy to allow 10 minutes instead of 4:

https://github.com/VertebrateResequencing/wr/compare/VertebrateResequencing:develop...keiranmraine:feature/incTimeOut

**Comment by sb10** [comment]
Thanks for the report and patch. I'll look in to making this a volume-specific timeout, ideally for when there are volume-creation issues (or scale the timeout with requested volume size?).

**Comment by sb10** [comment]
As per #49, if a new server is requested with a delete-on-terminate volume, but wr's own timeout on the server becoming READY is reached, wr's request to delete the server does not result in the deletion of the volume.

With the server timeout higher (600s) the volume does not get left behind, but the instance still fails to start.

**Comment by sb10** [comment]
Unfortunately I can't reproduce this at small scale. Testing with very small timeouts doesn't reveal anything I can fix in wr. I've implemented a 20min timeout now, which means you can still have servers fail to start, but those events should be "harmless": your volume quota won't get used up and wr will keep trying to start a server.

If you still end up with detached volumes, please re-open this issue with additional details, such as information on the volume that got stuck, and wr manager logs around the time the volume got created.
