### ISSUE TITLE
OpenStack scheduler: timed-out servers leave behind volumes

### ISSUE THREAD

**Issue by sb10** [VertebrateResequencing/wr#49]
@dkj reports that if a new server is requested with a delete-on-terminate volume, but wr's own timeout on the server becoming READY is reached, wr's request to delete the server does not result in the deletion of the volume.

**Comment by keiranmraine** [comment]
To confirm.  With the server timeout higher (600s) I'm not seeing the volumes being left behind, but the instance still fails to start, which I assume is due to the volume creation itself timing out.

**Comment by sb10** [comment]
Thanks. This is actually a duplicate of #48.
