### ISSUE TITLE
wr build fails to 'go get'

### ISSUE THREAD

**Issue by keithj** [VertebrateResequencing/wr#50]
Building wr from source I get this error message with a fresh binary install
of Go:

$ go version
go version go1.7.5 linux/amd64

[kdj@sf2-farm-srv2 go]$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/nfs/users/nfs_k/kdj/dev/external/go"
GORACE=""
GOROOT="/nfs/users/nfs_k/kdj/.local/lib/go"
GOTOOLDIR="/nfs/users/nfs_k/kdj/.local/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build000434645=/tmp/go-build"
CXX="g++"
CGO_ENABLED="1"

$ go get -u -d -tags netgo github.com/VertebrateResequencing/wr
package github.com/pivotal-golang/bytefmt: code in directory /nfs/users/nfs_k/kdj/dev/external/go/src/github.com/pivotal-golang/bytefmt expects import "code.cloudfoundry.org/bytefmt"

Looks like a change to canonical import path

https://github.com/cloudfoundry/bytefmt/commit/4ca94c81cb8f51302e44e42f9e8be9503cba8d70

**Comment by sb10** [comment]
Yes, thank you for taking the time to write up an issue. Already fixed on develop branch.
