### ISSUE TITLE
OpenStack scheduler: servers get oversubscribed

### ISSUE THREAD

**Issue by sb10** [VertebrateResequencing/wr#55]
Testing with testjobsOpenStackDelta, things ramp up to my quota getting full, but hits a steady state of 137 running simultaneously on 128 cores. So somehow some of the (all 2 core) servers are running more than 2 jobs.

**Comment by sb10** [comment]
Repeatable; second time it hit 133 simultaneous on 128 cores.

**Comment by keiranmraine** [comment]
I saw 34 on a host with only 1 executing job (24 core)

**Comment by sb10** [comment]
Fixed for my test case, should also fix @keiranmraine's, but please reopen if not.
