### ISSUE TITLE
web-interface: remove button doesn't work

### ISSUE THREAD

**Issue by keiranmraine** [VertebrateResequencing/wr#68]
Submitted a batch of jobs (45) that couldn't be handled by available flavours so all were instantly buried.  Clicking 'Remove' resulted in no action.

**Comment by sb10** [comment]
I'm also suffering from this. Must be a recently introduced bug.

**Comment by sb10** [comment]
It was a failure to push a change to the web page in a prior commit that caused this. Should be working fine now.
