### ISSUE TITLE
Job Behaviours system

### ISSUE THREAD

**Issue by sb10** [VertebrateResequencing/wr#71]
There should be a generic behaviours system allowing the user to specify that something happens before/after a job is executed.

Perhaps the `wr add` json might be:

    mycmd in > out {"post_behaviours":[{"when":"always","what":"cleanup"}]}

Which would delete all contents of cwd after the command exited.

More complex:

    mycmd in > out {"post_behaviours":[{"when":"failure","what":"cmd","details":"tar -czf my.tar.bz '--include=*.err'"}{"when":"failure","what":"copy_to_manager","details":"my.tar.bz"}]}

Where copy_to_manager scp's the given file to the manager's log directory, filename uniqueified in some way that can be correlated to the job that created it. Or we just store the unique filename we came up with, and report it in status.

**Comment by keiranmraine** [comment]
Yes, looks good. Transferred file could be given the hosts name plus the `pid` of the job that failed (I can see this in the web-details so assume it's available for this).

I essentially have cleanup embedded in my main command at present:

```
rm -rf /tmp/tmp* /tmp/datastore && <ACTUAL WORK> &&rm -rf /tmp/tmp* /tmp/datastore
```

**Comment by dkj** [comment]
I think `what` a little ambiguous: I initially parsed the second example as on `failure` of `cmd`. Would `do` more tightly describe what is happening than `what`?

The multi-function content of `details` isn't to my taste (buy hey, I not writing the code so I'll take what I'm given!). 

How about the (maybe) simpler alternative:
```
{"cmd":"mycmd in > out", "post_behaviours":[{"when":"failure","cmd":"tar -czf my.tar.bz '--include=*.err'","copy_to_manager":"my.tar.bz"}]}
```
or even:
```
{"cmd":"mycmd in > out", "on_failure":{"cmd":"tar -czf my.tar.bz '--include=*.err'","copy_to_manager":"my.tar.bz"}}
```

**Comment by sb10** [comment]
I think there needs to be a clear ordered list of what you want to happen, so your first alternative doesn't work for me, but we can save some repetition from my example by using an array based on your second alternative:

    mycmd in > out {"on_failure":[{"run":"tar -czf my.tar.bz '--include=*.err'"},{"copy_to_manager":"my.tar.bz"},{"cleanup":true}], "on_success":[{"cleanup":true}]}

The default would be:

    {"on_exit":[{"cleanup":true}]}

The `{"cleanup":true}` behaviour wipes out cwd only if wr created cwd (ie. we're in unique_cwd mode).

**Comment by sb10** [comment]
Now implemented (develop branch), except for the "copy_to_manager" behaviour, which is more involved. It's still needed, however, because you can't easily do something like copy files to s3 using muxfys mounts, because we must unmount before running behaviours.

**Comment by sb10** [comment]
Behaviours now run before unmounting, and the cleanup behaviour "does the right thing" and doesn't mess with the mounts. So now you can just copy your logs to somewhere in your bucket instead, as part of your run behaviour. For this reason "copy_to_manager" won't be implemented unless someone shouts for it.
