### ISSUE TITLE
OpenStack scheduler: handle slow spawns better

### ISSUE THREAD

**Issue by sb10** [VertebrateResequencing/wr#76]
Currently, wr learns how long instances take to spawn, and then if an instance takes 4x this time, it is terminated.

But if we have lots of quick spawns followed by a much slower one (because now we're spawning on a new physical host which hasn't cached anything), we unnecessarily kill good instances.

Instead we should only kill spawns after a fixed large timeout (20mins, or 4x learned value, which ever is larger); once they take longer than the learned spawn timeout x4, we simply allow moving on to the next spawn attempt.

**Comment by keiranmraine** [comment]
There still needs to be a base time, e.g.

```
timeout_val = max( 90, 4*learned )
```

**Comment by sb10** [comment]
To be clear, you're suggesting we ought to wait at least 90s before attempting a new spawn, if the previous spawn is taking longer than normal?

What does this represent? Trying not to overload the system during a period of slowness?

**Comment by sb10** [comment]
```
2017/10/04 21:34:39 p 7f0a97c9-e9eb-4557-b25d-48b7b22915a0 spawned
2017/10/04 21:34:39 q 7f0a97c9-e9eb-4557-b25d-48b7b22915a0 locked
2017/10/04 21:34:39 t 7f0a97c9-e9eb-4557-b25d-48b7b22915a0 unlocked prior to waiting for server to become ready
2017/10/04 21:34:39 u 7f0a97c9-e9eb-4557-b25d-48b7b22915a0 locked after waiting for server to become ready
2017/10/04 21:34:39 server  Destroy() called DestroyServer() and got err Resource not found
2017/10/04 21:34:39 v 7f0a97c9-e9eb-4557-b25d-48b7b22915a0 will fail standin due to err timed out waiting for server to become ACTIVE
```

Did the expected spawn time somehow become 0? Maybe we need a base time just for this reason.

**Comment by sb10** [comment]
Changed mind about moving on to the next spawn and having a very large spawn timeout; instead just added the minimum timeout of 90s.
