### ISSUE TITLE
deploy --config_files from:to

### ISSUE THREAD

**Issue by keiranmraine** [VertebrateResequencing/wr#88]
Looks like they system attempts to put the file in the same path rather than in the images native users home directory (e.g. /home/ubuntu)

```
$ wr cloud deploy -f '^m.*$' -c "$HOME/.s3cfg"
info: please wait while openstack resources are created...
info: please wait while a server is spawned on openstack...
info: please wait while I start 'wr manager' on the openstack server at 172.27.87.86...
error: failed to upload wr cloud config files to the server at 172.27.87.86: cloud RunCmd(mkdir -p /nfs/my_network_source/home) failed: Process exited with status 1
```

**Comment by sb10** [comment]
You must use the form "~/.s3cfg", as per the default. I'll clarify this better in the main help text.

**Comment by keiranmraine** [comment]
@sb10, have you considered making this more flexible?  For example to following would allow local and remote paths to be defined for the config files

```
-c 'projectSpecific/.s3cfg:~/.s3cfg
```

**Comment by sb10** [comment]
Yes, it would be useful to optionally specify from:to.

**Comment by sb10** [comment]
Implemented
